version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  backend:
    depends_on:
      - mysqldb
    image: commercialeplatforme/gestion-commercial-backend:latest
    container_name: gestion-commercial-backend
    build: ./back-end
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

  frontend: 
    image: commercialeplatforme/gestion-commercial-frontend:latest
    container_name: gestion-commercial-frontend
    build: ./front-end/my-app
    volumes:
      - './:/usr/src/app'
    ports:
      - $ANGULAR_LOCAL_PORT:$ANGULAR_DOCKER_PORT

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysqldb
      - PMA_USER=root
      - PMA_PASSWORD=$MYSQLDB_ROOT_PASSWORD
    ports:
      - $PHPMYADMIN_LOCAL_PORT:80
    links:
      - mysqldb

volumes:
  db:
